### Module :

====>>> Collection of / set of function defination with in the python file

### Package :

===>>> Collection of modules with in the one folder

#### Types of Modules and packages( libreries )

###### 1. Pre defined module and packages

=======>>> The modules / Pacakages which are already defined inside python

========>>> math , cmath, os, re, thread, multithread, socket,time, random, ctype

######  2. Semi- pre defined Module and packages

====>>> The modules and packages which are not available inside of python

===>>> the modules and packages which are available on internet--> download---> install

====>>> then we can use pre defined module

====>> numpy, pandas,matplotlib,sklearn,django,flask,tkinter

###### 3. User defined Module and packages

===>>> The modules and packages which are defined by programmer

#### How to use  module and packages

====>>> import   , from   , as 

In [2]:
import math
print dir(math)
print help(math.acos)

['__doc__', '__name__', '__package__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'hypot', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'modf', 'pi', 'pow', 'radians', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'trunc']
Help on built-in function acos in module math:

acos(...)
    acos(x)
    
    Return the arc cosine (measured in radians) of x.

None


In [8]:
import math
print math.sqrt(16)
print math.log10(10)
print math.pi
print math.ceil(34.99999)
print math.ceil(34.00001)
print math.floor(34.00001)# 34
print math.floor(34.9999999)# 34

4.0
1.0
3.14159265359
35.0
35.0
34.0
34.0


In [9]:
import math as ma
print ma.sqrt(16)
print ma.log10(10)
print ma.pi
print ma.ceil(34.99999)
print ma.ceil(34.00001)
print ma.floor(34.00001)# 34
print ma.floor(34.9999999)# 34

4.0
1.0
3.14159265359
35.0
35.0
34.0
34.0


In [11]:
from math import ceil, floor

print ceil(34.99999)
print ceil(34.00001)
print floor(34.00001)# 34
print floor(34.9999999)# 34
print sqrt(16)
print log10(10)
print pi

35.0
35.0
34.0
34.0


NameError: name 'sqrt' is not defined

In [13]:
from math import *

print ceil(34.99999)
print ceil(34.00001)
print floor(34.00001)# 34
print floor(34.9999999)# 34
print sqrt(16)
print log10(10)
print pi

35.0
35.0
34.0
34.0
4.0
1.0
3.14159265359


In [14]:
import numpy
var = numpy.array([1,2,3])
print var

[1 2 3]


In [15]:
import numpy as np
var = np.array([1,2,3])
print var

[1 2 3]


In [17]:
from numpy import array
var = array([1,2,3])
print var

[1 2 3]


In [18]:
from numpy import *
var = numpy.array([1,2,3])
print var

[1 2 3]


In [20]:
import sample
sample.fun1()
sample.fun2()

fun1
fun2


In [22]:
import sample as sm
sm.fun1()
sm.fun2()

fun1
fun2


In [24]:
from sample import fun1
fun1()
fun2()

fun1


NameError: name 'fun2' is not defined

In [26]:
from sample import *
fun1()
fun2()

fun1
fun2


In [28]:
import package
package.fun11()
package.fun22()
package.fun33()

fun11
fun22
fun33


In [30]:
import package as pack
pack.fun11()
pack.fun22()
pack.fun33()

fun11
fun22
fun33


In [32]:
from package import fun11
fun11()
fun22()
fun33()

fun11


NameError: name 'fun22' is not defined

In [34]:
from package import *
fun11()
fun22()
fun33()

fun11
fun22
fun33


In [ ]:
### create a operator package
# module1 ---> arithmetic.py ( add , sub , mul)
# module2 ---> logical.py (Not , AND, OR)
